In [3]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [22]:
p = [1095.95, 596.95, 896.95]

In [23]:
c = 30.1

In [24]:
prices = np.array(p)

In [25]:
prices * c

array([32988.095, 17968.195, 26998.195])

In [26]:
grades = np.array([85, 70, 82])

In [28]:
weights = np.array([0.3, 0.4, 0.3])

In [31]:
g = grades * weights

In [32]:
g

array([25.5, 28. , 24.6])

In [33]:
g.sum()

78.1

In [34]:
np.dot(grades, weights)  # np.dot() 是乘積

78.1

In [4]:
grades = np.array([[85, 70, 82], [75, 92, 85], [66, 67, 64], [87, 94, 60]])

In [5]:
grades

array([[85, 70, 82],
       [75, 92, 85],
       [66, 67, 64],
       [87, 94, 60]])

In [6]:
weights = np.array([0.3, 0.4, 0.3])

In [7]:
np.dot(grades, weights)

array([78.1, 84.8, 65.8, 81.7])

In [8]:
A = np.random.randn(100)  # 平均值 0，標準差 1 的一維矩陣

In [9]:
A

array([-1.68147394,  0.68722338, -0.01327964,  0.6653662 ,  0.44326763,
       -0.06664379,  0.67599484,  1.23370362,  1.21216824,  0.85202125,
        0.21525865, -0.69563025,  1.03164891,  2.23873428, -0.22050894,
       -1.27117351, -0.73741588,  0.39667367, -0.13166957,  0.06232832,
       -0.49377347,  1.23133972,  0.3728124 ,  2.058877  , -3.03317598,
       -0.58332974,  0.0678439 ,  2.69883192, -0.47710949, -0.32299049,
        0.25561044, -0.18327074, -0.56236933,  0.14967623,  1.47084434,
        3.0925911 , -0.26709081,  0.75050892, -0.04763712, -0.04406301,
       -0.77932637, -0.12743591, -2.23250391,  1.07519346, -1.15460842,
        0.34663648,  0.29484   ,  1.14679801, -0.35024361,  2.32716064,
        1.50916955,  0.21638792, -0.11656637,  0.07316025,  0.01933755,
        1.38197473, -0.12970284, -0.2335126 , -0.65295594, -0.16865131,
        0.10406141,  0.78846259, -0.3923369 , -0.45970012,  0.22578791,
        0.03351704,  0.47078747,  0.78179377, -0.27384457, -1.66

In [10]:
A = 10*A + 50  # 標準差 10，平均值 50 的一維矩陣

In [11]:
A

array([33.18526063, 56.87223381, 49.86720357, 56.65366202, 54.43267634,
       49.3335621 , 56.75994838, 62.33703623, 62.1216824 , 58.52021249,
       52.15258652, 43.0436975 , 60.31648914, 72.38734282, 47.79491064,
       37.28826488, 42.62584116, 53.96673668, 48.68330427, 50.62328315,
       45.06226534, 62.31339724, 53.72812403, 70.58877001, 19.66824025,
       44.16670262, 50.678439  , 76.98831924, 45.22890505, 46.77009506,
       52.55610437, 48.16729257, 44.37630665, 51.4967623 , 64.70844343,
       80.925911  , 47.32909187, 57.50508921, 49.5236288 , 49.55936988,
       42.20673629, 48.72564085, 27.67496092, 60.75193461, 38.45391581,
       53.46636477, 52.94839998, 61.46798015, 46.4975639 , 73.27160643,
       65.09169547, 52.16387923, 48.83433635, 50.73160254, 50.19337546,
       63.81974733, 48.70297162, 47.66487396, 43.47044063, 48.31348687,
       51.0406141 , 57.88462592, 46.07663097, 45.40299877, 52.25787908,
       50.3351704 , 54.70787468, 57.8179377 , 47.26155429, 33.39

In [13]:
A.shape    # 矩陣 A 的維度，一維：100、二維：0

(100,)

In [14]:
A.shape = (5, 20) # 將矩陣 A 轉變成一維：5、二維：20 的二維矩陣，一維與二維相乘必須是 100

In [15]:
A

array([[33.18526063, 56.87223381, 49.86720357, 56.65366202, 54.43267634,
        49.3335621 , 56.75994838, 62.33703623, 62.1216824 , 58.52021249,
        52.15258652, 43.0436975 , 60.31648914, 72.38734282, 47.79491064,
        37.28826488, 42.62584116, 53.96673668, 48.68330427, 50.62328315],
       [45.06226534, 62.31339724, 53.72812403, 70.58877001, 19.66824025,
        44.16670262, 50.678439  , 76.98831924, 45.22890505, 46.77009506,
        52.55610437, 48.16729257, 44.37630665, 51.4967623 , 64.70844343,
        80.925911  , 47.32909187, 57.50508921, 49.5236288 , 49.55936988],
       [42.20673629, 48.72564085, 27.67496092, 60.75193461, 38.45391581,
        53.46636477, 52.94839998, 61.46798015, 46.4975639 , 73.27160643,
        65.09169547, 52.16387923, 48.83433635, 50.73160254, 50.19337546,
        63.81974733, 48.70297162, 47.66487396, 43.47044063, 48.31348687],
       [51.0406141 , 57.88462592, 46.07663097, 45.40299877, 52.25787908,
        50.3351704 , 54.70787468, 57.8179377 , 4

In [17]:
A.reshape(100,1)  # 會在記憶體內產生一個新的 Array，不會改變原來的 A 

array([[33.18526063],
       [56.87223381],
       [49.86720357],
       [56.65366202],
       [54.43267634],
       [49.3335621 ],
       [56.75994838],
       [62.33703623],
       [62.1216824 ],
       [58.52021249],
       [52.15258652],
       [43.0436975 ],
       [60.31648914],
       [72.38734282],
       [47.79491064],
       [37.28826488],
       [42.62584116],
       [53.96673668],
       [48.68330427],
       [50.62328315],
       [45.06226534],
       [62.31339724],
       [53.72812403],
       [70.58877001],
       [19.66824025],
       [44.16670262],
       [50.678439  ],
       [76.98831924],
       [45.22890505],
       [46.77009506],
       [52.55610437],
       [48.16729257],
       [44.37630665],
       [51.4967623 ],
       [64.70844343],
       [80.925911  ],
       [47.32909187],
       [57.50508921],
       [49.5236288 ],
       [49.55936988],
       [42.20673629],
       [48.72564085],
       [27.67496092],
       [60.75193461],
       [38.45391581],
       [53

In [18]:
A  # reshape 後 A 還是沒變

array([[33.18526063, 56.87223381, 49.86720357, 56.65366202, 54.43267634,
        49.3335621 , 56.75994838, 62.33703623, 62.1216824 , 58.52021249,
        52.15258652, 43.0436975 , 60.31648914, 72.38734282, 47.79491064,
        37.28826488, 42.62584116, 53.96673668, 48.68330427, 50.62328315],
       [45.06226534, 62.31339724, 53.72812403, 70.58877001, 19.66824025,
        44.16670262, 50.678439  , 76.98831924, 45.22890505, 46.77009506,
        52.55610437, 48.16729257, 44.37630665, 51.4967623 , 64.70844343,
        80.925911  , 47.32909187, 57.50508921, 49.5236288 , 49.55936988],
       [42.20673629, 48.72564085, 27.67496092, 60.75193461, 38.45391581,
        53.46636477, 52.94839998, 61.46798015, 46.4975639 , 73.27160643,
        65.09169547, 52.16387923, 48.83433635, 50.73160254, 50.19337546,
        63.81974733, 48.70297162, 47.66487396, 43.47044063, 48.31348687],
       [51.0406141 , 57.88462592, 46.07663097, 45.40299877, 52.25787908,
        50.3351704 , 54.70787468, 57.8179377 , 4

In [19]:
# 如果要改變 A，可以重新指派

A = A.reshape(100,1)  

In [20]:
A   # 重新指派後，A 就改變了

array([[33.18526063],
       [56.87223381],
       [49.86720357],
       [56.65366202],
       [54.43267634],
       [49.3335621 ],
       [56.75994838],
       [62.33703623],
       [62.1216824 ],
       [58.52021249],
       [52.15258652],
       [43.0436975 ],
       [60.31648914],
       [72.38734282],
       [47.79491064],
       [37.28826488],
       [42.62584116],
       [53.96673668],
       [48.68330427],
       [50.62328315],
       [45.06226534],
       [62.31339724],
       [53.72812403],
       [70.58877001],
       [19.66824025],
       [44.16670262],
       [50.678439  ],
       [76.98831924],
       [45.22890505],
       [46.77009506],
       [52.55610437],
       [48.16729257],
       [44.37630665],
       [51.4967623 ],
       [64.70844343],
       [80.925911  ],
       [47.32909187],
       [57.50508921],
       [49.5236288 ],
       [49.55936988],
       [42.20673629],
       [48.72564085],
       [27.67496092],
       [60.75193461],
       [38.45391581],
       [53

In [24]:
two_dim_matrix_one = np.array([[1, 2, 3], [4, 5, 6]])
two_dim_matrix_two = np.array([[1, 1], [1, 1], [1, 1]])
two_multi_res = np.dot(two_dim_matrix_one, two_dim_matrix_two)
print('two_multi_res: %s' %(two_multi_res))

two_multi_res: [[ 6  6]
 [15 15]]
