In [5]:
import requests
from bs4 import BeautifulSoup

r = requests.get('https://www.google.com/search?q=python3')
soup = BeautifulSoup(r.text, 'lxml')

for ii in soup.find_all('h3'):
    print(ii.text)

Python3 教程| 菜鸟教程
Download Python | Python.org
Python 3.0 Release | Python.org
Python 3 Tutorial 第一堂（2）哈囉！世界！ - OpenHome.cc
Python3 函數- Python3入門基礎教程 - 極客書
Python3 隨機數- Python3入門基礎教程 - 極客書
Python 3 | ActiveState
Python 3 - Trinket
給自學者的Python教學(0) : 如何安裝Python(Mac/Windows) – Chun ...
老灰鴨的筆記本: 【Python】CentOS7 安裝Python3


In [4]:
from bs4 import BeautifulSoup
import requests
 
url = 'https://www.google.com/search?q=python3'
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 \
     (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}
res = requests.get(url, headers=headers)
soup = BeautifulSoup(res.text, 'lxml')
 
h3 = soup.select('div.r a h3')
for _ in h3:
    print(_.text)

Python3 教程| 菜鸟教程
Download Python | Python.org
Python 3.0 Release | Python.org
Python 3 Tutorial 第一堂（2）哈囉！世界！ - OpenHome.cc
Python3 函數- Python3入門基礎教程 - 極客書
Python3 隨機數- Python3入門基礎教程 - 極客書
Python 3 | ActiveState
Python 3 - Trinket
給自學者的Python教學(0) : 如何安裝Python(Mac/Windows) – Chun ...
老灰鴨的筆記本: 【Python】CentOS7 安裝Python3


In [14]:
import numpy as np
import pandas as pd

ndarray = np.arange(1,10).reshape(3,3)
print(ndarray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(ndarray[0])

[1 2 3]


In [8]:
print(ndarray[0][:]) # 取軸 0(y) 第一項然後對應的軸 1(x) 每項都要

[1 2 3]


In [22]:
print(ndarray[0, :])

[1 2 3]


In [9]:
print(ndarray[0][1]) # 先選取軸 0 的第 0 項,接著再對應取軸 1 的第 1 項

2


In [23]:
print(ndarray[0, 1])

2


In [20]:
print(ndarray[:][0:2])  # 表示軸 0 的項目全部都要,但只取每一項的軸 1 的 0 到 1 項  ？？？

[[1 2 3]
 [4 5 6]]


In [24]:
print(ndarray[:, 0:2])  # 表示軸 0 的項目全部都要,但只取每一項的軸 1 的 0 到 1 項

[[1 2]
 [4 5]
 [7 8]]


In [21]:
print(ndarray[0:2][:])  # 表示軸 0 的的 0 到 1 項,軸 1 的項目全部都要

[[1 2 3]
 [4 5 6]]


In [25]:
print(ndarray[0:2, :])  # 表示軸 0 的的 0 到 1 項,軸 1 的項目全部都要

[[1 2 3]
 [4 5 6]]


In [26]:
print(ndarray[0:2, 0:2])  # 表示軸 0 的 0 到 1 項,與軸 1 的 0 到 1 項

[[1 2]
 [4 5]]


In [16]:
print(ndarray.sum())

45


In [13]:
print(ndarray.sum(axis = 1)) # 將軸 1 的各項相加,但不將軸 0 合併(合併了軸 0 就等於一般 ndarray.sum()的結果了)

[ 6 15 24]


In [18]:
print(ndarray.sum(axis = 0)) # 將軸 0 的各項相加,但不將軸 1 合併(合併了軸 1 就等於一般 ndarray.sum()的結果了)

[12 15 18]


In [40]:
frame2 = pd.DataFrame(np.arange(1,10).reshape(3, 3), columns = list((0,1,2)), index = list((0,1,2)))
f = lambda x : x.max() - x.min()

print(frame2)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [41]:
frame2.apply(f, axis = 0)  # 從軸 0 各項中取最大項減最小項,不合併軸 1 (每行各自從其對應軸 0 各項中取 max 減 min)

0    6
1    6
2    6
dtype: int64

In [42]:
frame2.apply(f, axis = 1)  # 從軸 1 各項中取最大項減最小項,不合併軸 1 (每行各自從其對應軸 0 各項中取 max 減 min)

0    2
1    2
2    2
dtype: int64

In [10]:
f = lambda x, y: x + y
g = lambda x: x + 1

print(f(1, 2))
print(g(1))

3
2


In [22]:
exp1 = lambda x : x+1 if 2 == 1 else 0
print(exp1(1))

0
